// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200207195153");
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.user_id", "1d1aabff-1380-4065-afd5-f0196922020f");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1582012343);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1582012463);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1581974186);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1582012103);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1582011983);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1582012223);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1582012013);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1582012583);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 2551);
user_pref("browser.cache.disk.capacity", 419840);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1581974155);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 91);
user_pref("browser.newtabpage.activity-stream.impressionId", "{19073cd2-49ac-42eb-8cde-fa26d53a8d97}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1582012021728");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1582013828728");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1582011960075");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1582015560075");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200207195153");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1582011957");
user_pref("browser.slowStartup.averageTime", 4678);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200207195153");
user_pref("browser.startup.homepage_override.mstone", "73.0");
user_pref("browser.startup.lastColdStartupCheck", 1582011955);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1581974163254");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "73.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "30513a4ccabb4b259a5e11a026a93c88");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1582012344);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "73.0");
user_pref("extensions.lastPlatformVersion", "73.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"d5e48611-fc9d-4d55-b967-123f9e3fe8f6\",\"formautofill@mozilla.org\":\"7763b279-3541-4e98-8b92-429011620f90\",\"screenshots@mozilla.org\":\"2c41f107-1ff5-42e7-935c-2e3b93075f85\",\"webcompat-reporter@mozilla.org\":\"f33d6453-5f98-4887-9e12-eb37efe9d87b\",\"webcompat@mozilla.org\":\"e091bd22-4373-403b-9431-31a1662de3cd\",\"default-theme@mozilla.org\":\"a7cbdf32-8234-45e9-bf7b-556cc32272f7\",\"google@search.mozilla.org\":\"9f1eb502-ee5f-4e57-9579-af023d678552\",\"amazondotcom@search.mozilla.org\":\"70dfa088-39a8-41ac-9f71-4aef5b668fc8\",\"bing@search.mozilla.org\":\"d88de321-aca8-4fc2-9478-c1e35158afff\",\"ddg@search.mozilla.org\":\"281b5794-511c-4b5d-899b-72f5a23b139d\",\"ebay@search.mozilla.org\":\"96b19aaa-d231-4214-9d89-9100fa357ee9\",\"twitter@search.mozilla.org\":\"5fd5786c-9c67-4a2c-8372-788209af420b\",\"wikipedia@search.mozilla.org\":\"6e8c0b89-93bb-4500-9b97-ca374ffff29b\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1582012164);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1582012005);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200207195153");
user_pref("media.gmp-manager.lastCheck", 1582012005);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1582012164);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "01009160-a276-46bf-bafb-5079f4120be8");
user_pref("security.sandbox.plugin.tempDirSuffix", "443b9a6f-db12-493e-9a49-763dce688b81");
user_pref("services.blocklist.addons.checked", 1582012097);
user_pref("services.blocklist.gfx.checked", 1582012097);
user_pref("services.blocklist.pinning.checked", 1582012097);
user_pref("services.blocklist.plugins.checked", 1582012097);
user_pref("services.settings.clock_skew_seconds", -18);
user_pref("services.settings.last_etag", "\"1581976608692\"");
user_pref("services.settings.last_update_seconds", 1582012241);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1582012097);
user_pref("services.settings.main.cfr-fxa.last_check", 1582012097);
user_pref("services.settings.main.cfr.last_check", 1582012097);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1582012097);
user_pref("services.settings.main.hijack-blocklists.last_check", 1582012097);
user_pref("services.settings.main.language-dictionaries.last_check", 1582012097);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1582012097);
user_pref("services.settings.main.public-suffix-list.last_check", 1582012097);
user_pref("services.settings.main.sites-classification.last_check", 1582012097);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1582012097);
user_pref("services.settings.main.whats-new-panel.last_check", 1582012097);
user_pref("services.settings.security.onecrl.checked", 1582012097);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1582012164);
user_pref("toolkit.startup.last_success", 1582011950);
user_pref("toolkit.telemetry.cachedClientID", "cb1ebd4f-2593-4d0c-bcef-6281c46511b0");
user_pref("toolkit.telemetry.previousBuildID", "20200207195153");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
